<a href="https://colab.research.google.com/github/Furtivo4/AnalisisdeDatos/blob/main/AnalisisdeDatos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [6]:
#Crear arreglo de 1 dimension con varios elementos
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
print(arr1.shape)
print(arr1.dtype)

[1 2 3 4 5 6]
(6,)
int64


In [7]:
#Cambiar la forma del arreglo de una matriz
arr2 = arr1.reshape(2,3)
print(arr2)
print(arr2.shape)
print(arr2.dtype)

[[1 2 3]
 [4 5 6]]
(2, 3)
int64


In [11]:
#Crear una matriz 4x4 con numeros aleatorios
matrix = np.random.rand(4,4)
print(matrix)
print(matrix.shape)
print(matrix.dtype)

[[0.65879913 0.35502734 0.60192828 0.9626631 ]
 [0.98313746 0.30778709 0.37970534 0.85325434]
 [0.77181306 0.89507942 0.17176003 0.14256384]
 [0.56578955 0.43854763 0.69097493 0.50113132]]
(4, 4)
float64
